<a href="#criticalHits" >Critical Hits</a>
<a href="#resistanceTable" >Resistance Table</a>
<a href="#dieRoller" >Die Roller</a>
<a href="#herbLore" >Herb Lore</a>
<a href="#players" >Players</a>
<a href="#characterList" >Character List</a>
<a href="#itemList" >Item List</a>
<a href="#willContestList" >Will Contest List</a>
<a href="#movementManeuvers" >Movement Maneuvers</a>