<td><%- playerName %></td>
<td><%= characterName %></td>
<td><%= level %></td>
<td><%= miscItemChoice %></td>
<td><%= initiative %></td>
<td><%= initiativeModifier %></td>
<td><%= will %></td>
<td><%= willModifier %></td>
<td><%= observationSkill %></td>
<td><%= stalkSkill %></td>
<td><%= alertnessSkill %></td>
<td><%= senseAmbushSkill %></td>
<td><%= armorChoice %></td>
<td><%= hasAdrenalDefense %></td>
<td><%= totalDefensiveBonusMinusAdrenalDefense %></td>
<td><%= totalDefensiveBonusMinusAdrenalDefenseAndWeaponParry %></td>
<td data-toggle="tooltip" title="<%- totalDefensiveBonusDescription%>"><%= totalDefensiveBonus %></td>
<td><%= hasShield %></td>
<td><%= hitPoints %></td>
<td><%= hitPointsModifier %></td>
